---
abstract: 'OO Interface to ZMQ'
author:
  - 'Thomas Klausner <domm@plix.at>'
build_requires:
  Data::Dumper: '0'
  File::Temp: '0'
  JSON::XS: '0'
  Module::Build: '0.28'
  Test::More: '0'
  Test::Most: '0'
  Test::SharedFork: '0'
  bytes: '0'
  perl: '5.014'
  utf8: '0'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ZMQx-Class
requires:
  AnyEvent: '0'
  Carp: '0'
  Encode: '0'
  Log::Any: '0'
  Moose: '0'
  MooseX::Role::Parameterized: '0'
  Package::Stash: '0'
  ZMQ::Constants: '0'
  ZMQ::FFI: '0'
  constant: '0'
  namespace::autoclean: '0'
  perl: '5.014'
  strict: '0'
  warnings: '0'
resources:
  repository: git://devbox.vpn.validad.net/ZMQx-Class.git
version: '0.006'
